language:
  - cpp

compiler:
  - gcc

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get -qq install libglew-dev libsdl1.2-dev

script:
  - mkdir build
  - cd build
  - cmake -DTREAT_WARNINGS_AS_ERRORS=Off ..
  - make